allowBuilds:
  unrs-resolver: true

autoInstallPeers: true

enablePrePostScripts: false

engineStrict: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExcludePrune: true

overrides:
  brace-expansion@>=3.0.0 <5.0.7: ^5.0.7
